### ISSUE TITLE
Unable to obtain driver for MicrosoftEdge using Selenium Manager

### ISSUE THREAD

**Issue by Amovement** [XiaoJiang0208/TarkovMapTool#11]
发给朋友打包好的release运行的时候报错，如图：
![微信图片_20240216233236](https://github.com/XiaoJiang0208/TarkovMapTool/assets/48820654/d2ee1c80-7c01-427d-9561-a98d924cf729)

朋友在不是很懂软件开发的情况下很难教会他怎么把这个问题解决掉

**Comment by Amovement** [comment]
#12 
加了一行同目录下读 driver 的代码，这样直接把 driver 也打包发过去感觉轻松多了。

**Comment by XiaoJiang0208** [comment]
现在会自动从互联网拉取对应版本drive

**Comment by NamelessXiaoJiang** [comment]
现在会自动从互联网拉取对应版本drive
